### ISSUE TITLE
ssl socket support

### ISSUE THREAD

**Issue by erylee** [emqtt/emqtt#48]

**Comment by erylee** [comment]
upgrade deps/esockd to 0.2.0 to support ssl socket.

etc/app.config:

```
        {'mqtts', 8883, [
            {max_clients, 1024},
            {acceptor_pool, 4},
            %{cacertfile, "etc/ssl/cacert.pem"},
            {ssl, [{certfile, "etc/ssl.crt"},
                   {keyfile,  "etc/ssl.key"}]}
        ]},
```

**Comment by Ethanjfobrien** [comment]
How do you set up the config files to support a socket connection to the broker?
I'm trying to test using `wscat -c ws://localhost:8083/mqtt` but I get 

    error: Error: unexpected server response (400)

and the broker console output is:

    17:38:32.386 [info] Websocket Connection from: 127.0.0.1
    17:38:32.386 [error] WebSocket with error Protocol: undefined

Any help you can provide with this would be hugely appreciated!

**Comment by erylee** [comment]
@Ethanjfobrien, WebSocket should have 'Sec-WebSocket-Protocol' Header with value that start with 'mqtt'.

**Comment by erylee** [comment]
@Ethanjfobrien, WebSocket should have 'Sec-WebSocket-Protocol' Header with value that start with 'mqtt'.

**Comment by Ethanjfobrien** [comment]
Thanks very much,
I got it working using mqtt.js:

    mqtt pub -t 'hello' -l 'ws' -h 'localhost' -p '' -m 'hello' -v

wscat doesn't support the mqtt socket protocol

**Comment by erylee** [comment]
I use mqtt.js too:)
